# Kaggle - Brain Tumor MRI Dataset

You can find the dataset and some informations about on the [Kaggle page](https://www.kaggle.com/datasets/masoudnickparvar/brain-tumor-mri-dataset).

For details on steps below, please see documentation in the *docs* directory.

## Kaggle notebook setup
### Installations

In [29]:
!pip install mlflow --quiet

### Data location

In [30]:
import os
print(os.listdir('/kaggle/input/'))
print(os.listdir('/kaggle/input/radimagenet-densenet121-notop'))
print(os.listdir('/kaggle/input/brain-tumor-mri-preprocessed'))
print(os.listdir('/kaggle/input/brain-tumor-mri-preprocessed/processed'))

['radimagenet-densenet121-notop', 'brain-tumor-mri-preprocessed']
['RadImageNet-DenseNet121_notop.h5']
['processed']
['Validation', 'Training', 'Testing', '.gitkeep']

## General

In [73]:
import mlflow
import mlflow.tensorflow
from mlflow.tracking import MlflowClient
mlflow.set_tracking_uri("https://preachingly-nonabjuratory-marget.ngrok-free.dev")
mlflow.set_experiment("Brain_Tumor_Training")

<Experiment: artifact_location='mlflow-artifacts:/830660600119881173', creation_time=1769099937797, experiment_id='830660600119881173', last_update_time=1769099937797, lifecycle_stage='active', name='Brain_Tumor_Training', tags={'mlflow.experimentKind': 'custom_model_development'}>

In [32]:
import numpy as np

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.applications import DenseNet121
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping

import pandas as pd
import matplotlib.pyplot as plt

from pathlib import Path
from datetime import datetime
import math

In [33]:
tf.keras.mixed_precision.set_global_policy("mixed_float16")
print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))
tf.config.list_physical_devices('GPU')

Num GPUs Available: 1

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [71]:
# path management
PROJECT_ROOT = '/kaggle/input'
PREP_DIR = PROJECT_ROOT + '/brain-tumor-mri-preprocessed/processed'
ARTEFACTS_DIR = PROJECT_ROOT + '/radimagenet-densenet121-notop'

CHECKPOINT_DIR = "/kaggle/working/checkpoints"
os.makedirs(CHECKPOINT_DIR, exist_ok=True)
MODEL_DIR = "/kaggle/working/export_model"
os.makedirs(MODEL_DIR, exist_ok=True)

CLASSES = ["notumor", "glioma", "meningioma", "pituitary"]

# parameters
IMG_SIZE = 260
SEED = 42

PROJECT_NAME = "BrainTumorMRI"
MODEL_TYPE = "DenseNet121"
TWO_HEAD = True
MODEL_NAME = f"{PROJECT_NAME}_{MODEL_TYPE}_{TWO_HEAD*"2Head"}"
FREEZE_BACKBONE = True
MASK_TUMOR_TYPE_LOSS = True
BATCH_SIZE = 32
DATA_AUGMENTATION = True

## Modeling

### Backbone

In [35]:
# 1. Create DenseNet121 WITHOUT weights
backbone = DenseNet121(
    include_top=False,
    weights=None,
    input_shape=(IMG_SIZE, IMG_SIZE, 3)
)

# 2. Load RadImageNet weights
backbone.load_weights(ARTEFACTS_DIR + "/RadImageNet-DenseNet121_notop.h5")

# 3. Freeze the backbone for firsts training
backbone.trainable = not FREEZE_BACKBONE

print("✅ RadImageNet DenseNet121 loaded successfully")

✅ RadImageNet DenseNet121 loaded successfully

In [36]:
#backbone.summary()

In [37]:
w = backbone.weights[0].numpy()
print("Mean:", np.mean(w), "Std:", np.std(w))

Mean: -0.0028284893 Std: 0.10494729

Model seems to be correctly loaded.

### Model definition

In [38]:
model_data_augmentation = keras.Sequential([
    layers.RandomFlip("horizontal", seed=SEED),
    layers.RandomZoom((-0.03,0.03),(-0.03,0.03), seed=SEED),
    layers.RandomTranslation((-0.01,0.01),(-0.01,0.01), seed=SEED),
], name='data_augmentation_part')

In [39]:
model_head1 = keras.Sequential([
    layers.Dense(128, use_bias=False), # TO TEST : 256 ?
    layers.BatchNormalization(),
    layers.Activation('relu'),
    layers.Dropout(0.2),
    layers.Dense(1,activation='sigmoid')
], name='tumor_presence')

In [40]:
model_head2 = keras.Sequential([
    layers.Dense(128, use_bias=False), # TO TEST : 256 ?
    layers.BatchNormalization(),
    layers.Activation('relu'),
    layers.Dropout(0.2),
    layers.Dense(4,activation='softmax')
], name='tumor_type')

In [41]:
def shared_head_part(inputs, backbone, data_augmentation):
    # Data augmentation (training only)
    x = data_augmentation(inputs)
    # Backbone - force into inference
    x = backbone(x, training=False)

    # Shared head
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dense(512, use_bias=False)(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation('relu')(x)
    x = layers.Dropout(0.4)(x)

    return x

In [42]:
inputs = keras.Input(shape=(IMG_SIZE, IMG_SIZE, 3))

x = shared_head_part(inputs, backbone, model_data_augmentation)

#Heads
output_presence = model_head1(x)
output_type = model_head2(x)

model = keras.Model(
    inputs=inputs,
    outputs={
        "tumor_presence": output_presence,
        "tumor_type": output_type
    },
    name='densenet_two_head'
)

In [43]:
loss_presence = keras.losses.BinaryFocalCrossentropy(
    gamma=2.0,
    alpha=0.25 # to favorize tumor detection (penalize false negatives), but taking account that tumors are 75% of data
)

In [78]:
#@keras.saving.register_keras_serializable()
@tf.keras.utils.register_keras_serializable()
def masked_sparse_cce(y_true, y_pred):
    tumor_present = tf.cast(y_true != 0, tf.float32)
    loss = tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred)
    loss = loss * tumor_present
    return tf.reduce_sum(loss) / (tf.reduce_sum(tumor_present) + 1e-6)

In [79]:
loss_weight_presence = 1.0
loss_weight_type = 1.3 # we give a little more weight to the classification of the type

model.compile(
    optimizer=keras.optimizers.Adam(), # change learning_rate for 1e-4 in fine-tuning steps
    loss={
        "tumor_presence": loss_presence,
        "tumor_type": masked_sparse_cce,
    },
    
    loss_weights={
        "tumor_presence": loss_weight_presence,
        "tumor_type": loss_weight_type, 
    },
    
    metrics={
        "tumor_presence": [
            keras.metrics.BinaryAccuracy(name="accuracy"),
            keras.metrics.Recall(name="recall"),
            keras.metrics.Precision(name="precision"),
            #keras.metrics.F1Score(name="f1_score"),
            keras.metrics.AUC(name="auc")
        ],
        "tumor_type": [
            "accuracy", 
            #"f1_score"
        ],
    }
)

In [46]:
#model.summary()

## Streaming Training

In [47]:
def parse_tfrecord(example_proto):
    """
    Parse a single TFRecord example and convert grayscale → RGB.
    """
    feature_description = {
        "image": tf.io.FixedLenFeature([], tf.string),
        "label": tf.io.FixedLenFeature([], tf.int64),
    }

    example = tf.io.parse_single_example(example_proto, feature_description)

    # Deserialize image
    image = tf.io.parse_tensor(example["image"], out_type=tf.float32)

    # Shape after loading: (260, 260, 3)
    image.set_shape((260, 260, 3))

    label = tf.cast(example["label"], tf.int32)

    return image, label



def load_tfrecord_dataset(tfrecord_dir, shuffle=False, batch_size=1, repeat=False):
    """
    Load a TFRecord dataset from a directory.

    Args:
        tfrecord_dir (str or Path): Folder containing .tfrecord files
        shuffle (bool): Whether to shuffle files and samples
        batch_size (int): Batch size (can stay 1)
        repeat (bool): Repeat dataset indefinitely (for training)

    Returns:
        tf.data.Dataset
    """
    tfrecord_files = tf.io.gfile.glob(
        str(tfrecord_dir) + "/*.tfrecord"
    )

    ds = tf.data.TFRecordDataset(
        tfrecord_files,
        num_parallel_reads=tf.data.AUTOTUNE
    )

    ds = ds.map(
        parse_tfrecord,
        num_parallel_calls=tf.data.AUTOTUNE
    )

    if shuffle:
        ds = ds.shuffle(buffer_size=512)

    if repeat:
        ds = ds.repeat()

    ds = ds.batch(batch_size)
    ds = ds.prefetch(tf.data.AUTOTUNE)

    return ds

In [48]:
TRAIN_DIR = PREP_DIR + "/Training"
VAL_DIR   = PREP_DIR + "/Validation"
TEST_DIR  = PREP_DIR + "/Testing"

train_ds = load_tfrecord_dataset(
    TRAIN_DIR,
    shuffle=True,
    batch_size=BATCH_SIZE,
    repeat=False
).prefetch(tf.data.AUTOTUNE)

val_ds = load_tfrecord_dataset(
    VAL_DIR,
    shuffle=False,
    batch_size=BATCH_SIZE,
    repeat=False
).prefetch(tf.data.AUTOTUNE)

"""
test_ds = load_tfrecord_dataset(
    TEST_DIR,
    shuffle=False,
    batch_size=BATCH_SIZE,
    repeat=False
).prefetch(tf.data.AUTOTUNE)
"""

'\ntest_ds = load_tfrecord_dataset(\n    TEST_DIR,\n    shuffle=False,\n    batch_size=BATCH_SIZE,\n    repeat=False\n).prefetch(tf.data.AUTOTUNE)\n'

In [49]:
def split_labels(image, label):
    """
    Create labels for a 2-head model.
    """
    tumor_present = tf.cast(label != 0, tf.float32)
    tumor_type = tf.cast(label, tf.int32)

    return image, {
        "tumor_presence": tumor_present,
        "tumor_type": tumor_type
    }

In [50]:
train_ds = train_ds.map(split_labels, num_parallel_calls=tf.data.AUTOTUNE)
val_ds = val_ds.map(split_labels, num_parallel_calls=tf.data.AUTOTUNE)

In [51]:
#for x, y in train_ds.take(1):
#    print("Image:")
#    print(x.dtype, x.shape)
#    print("\nLabels:")
#    for k, v in y.items():
#        print(k, v.dtype, v.shape)

In [52]:
def count_tfrecord_batches(directory_path, batch_size):
    """
    Count number of batches for a TFRecord dataset.

    Assumes:
    - 1 sample per TFRecord
    - batch_size is variable

    Returns:
    - number of batches = ceil(num_samples / batch_size)
    """
    directory_path = Path(directory_path)
    n_samples = len(list(directory_path.glob("*.tfrecord")))
    return math.ceil(n_samples / batch_size)

In [53]:
print(train_ds.element_spec)

(TensorSpec(shape=(None, 260, 260, 3), dtype=tf.float32, name=None), {'tumor_presence': TensorSpec(shape=(None,), dtype=tf.float32, name=None), 'tumor_type': TensorSpec(shape=(None,), dtype=tf.int32, name=None)})

In [54]:
#to_monitor = "val_tumor_presence_recall"
#mode = "max"
to_monitor = "val_tumor_type_loss"
mode = "min"

reduce_lr = ReduceLROnPlateau(
    monitor=to_monitor,
    mode=mode,
    factor=0.5,
    patience=5,
    min_lr=1e-6,
    verbose=1
)

early_stopping = EarlyStopping(
    monitor=to_monitor,
    mode=mode,
    min_delta=0.0001,
    patience=10,
    restore_best_weights=False,
    verbose=1,
)

checkpoint_cb = keras.callbacks.ModelCheckpoint(
    filepath=CHECKPOINT_DIR + "/epoch_{epoch:02d}.weights.h5",
    monitor=to_monitor,
    mode=mode,
    save_best_only=False,
    save_weights_only=True,
    verbose=1,
)

terminate_nan = keras.callbacks.TerminateOnNaN()

In [55]:
#print("RUN_NAME:", RUN_NAME)
#print("TRAIN steps:", count_tfrecord_batches(TRAIN_DIR, BATCH_SIZE))
#print("VAL steps:", count_tfrecord_batches(VAL_DIR, BATCH_SIZE))
#print("train_ds element_spec:", train_ds.element_spec)

In [56]:
raise Exception("Do not fit from scratch again. Use the best head model !")

RUN_NAME = (
    f"{MODEL_TYPE}"
    f"freeze={FREEZE_BACKBONE}_"
    f"mask={MASK_TUMOR_TYPE_LOSS}_"
    f"{datetime.now().strftime('%Y%m%d-%H%M')}"
)

print(f"Run name: {RUN_NAME}\n")

with mlflow.start_run(run_name=RUN_NAME):

    mlflow.tensorflow.autolog(registered_model_name=MODEL_NAME)

    mlflow.log_params({
        "project": PROJECT_NAME,
        "model_type": MODEL_TYPE,
        "pretrained_weights": "RadImageNet",
        "backbone_frozen": FREEZE_BACKBONE,
        "head_1": "tumor_presence_binary",
        "head_2": "tumor_type_softmax",
        "loss_weight_presence": loss_weight_presence,
        "loss_weight_type": loss_weight_type,
        "mask_tumor_type_loss": MASK_TUMOR_TYPE_LOSS,
        "label_0_means": "no_tumor",
        "data_augmentation": DATA_AUGMENTATION,
    })

    history = model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=60,
        #steps_per_epoch=count_tfrecord_batches(TRAIN_DIR, BATCH_SIZE),
        #validation_steps=count_tfrecord_batches(VAL_DIR, BATCH_SIZE),
        callbacks=[reduce_lr, early_stopping, checkpoint_cb, terminate_nan],
        verbose=1,
    )

    client = MlflowClient()
    latest_version = client.get_latest_versions(MODEL_NAME)[-1].version

    client.transition_model_version_stage(
        name=MODEL_NAME,
        version=latest_version,
        stage="Staging"
    )

Run name: DenseNet121freeze=True_mask=True_20260204-1641

2026/02/04 16:41:06 WARNING mlflow.data.tensorflow_dataset: Failed to infer schema for TensorFlow dataset. Exception: Failed to infer schema for tf.data.Dataset. Schemas can only be inferred if the dataset consists of tensors. Ragged tensors, tensor arrays, and other types are not supported. Additionally, datasets with nested tensors are not supported.
2026/02/04 16:41:08 WARNING mlflow.data.tensorflow_dataset: Failed to infer schema for TensorFlow dataset. Exception: Failed to infer schema for tf.data.Dataset. Schemas can only be inferred if the dataset consists of tensors. Ragged tensors, tensor arrays, and other types are not supported. Additionally, datasets with nested tensors are not supported.

Epoch 1/60
    143/Unknown 36s 143ms/step - loss: 1.2487 - tumor_presence_accuracy: 0.7790 - tumor_presence_auc: 0.8119 - tumor_presence_loss: 0.1504 - tumor_presence_precision: 0.8613 - tumor_presence_recall: 0.8285 - tumor_type_accuracy: 0.4994 - tumor_type_loss: 0.8449
Epoch 1: saving model to /kaggle/working/checkpoints/epoch_01.weights.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

143/143 ━━━━━━━━━━━━━━━━━━━━ 68s 363ms/step - loss: 1.2470 - tumor_presence_accuracy: 0.7794 - tumor_presence_auc: 0.8124 - tumor_presence_loss: 0.1501 - tumor_presence_precision: 0.8615 - tumor_presence_recall: 0.8289 - tumor_type_accuracy: 0.4997 - tumor_type_loss: 0.8437 - val_loss: 1.5131 - val_tumor_presence_accuracy: 0.3185 - val_tumor_presence_auc: 0.9626 - val_tumor_presence_loss: 0.4738 - val_tumor_presence_precision: 1.0000 - val_tumor_presence_recall: 0.0546 - val_tumor_type_accuracy: 0.4339 - val_tumor_type_loss: 0.7674 - learning_rate: 0.0010
Epoch 2/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 0.7863 - tumor_presence_accuracy: 0.8853 - tumor_presence_auc: 0.9320 - tumor_presence_loss: 0.0805 - tumor_presence_precision: 0.9147 - tumor_presence_recall: 0.9275 - tumor_type_accuracy: 0.5530 - tumor_type_loss: 0.5429
Epoch 2: saving model to /kaggle/working/checkpoints/epoch_02.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 178ms/step - loss: 0.7860 - tumor_presence_accuracy: 0.8853 - tumor_presence_auc: 0.9321 - tumor_presence_loss: 0.0805 - tumor_presence_precision: 0.9148 - tumor_presence_recall: 0.9275 - tumor_type_accuracy: 0.5531 - tumor_type_loss: 0.5427 - val_loss: 2.8471 - val_tumor_presence_accuracy: 0.5906 - val_tumor_presence_auc: 0.8920 - val_tumor_presence_loss: 0.2670 - val_tumor_presence_precision: 0.9564 - val_tumor_presence_recall: 0.4527 - val_tumor_type_accuracy: 0.2616 - val_tumor_type_loss: 1.9255 - learning_rate: 0.0010
Epoch 3/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 0.6281 - tumor_presence_accuracy: 0.9083 - tumor_presence_auc: 0.9549 - tumor_presence_loss: 0.0662 - tumor_presence_precision: 0.9313 - tumor_presence_recall: 0.9432 - tumor_type_accuracy: 0.5961 - tumor_type_loss: 0.4322
Epoch 3: saving model to /kaggle/working/checkpoints/epoch_03.weights.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

143/143 ━━━━━━━━━━━━━━━━━━━━ 48s 330ms/step - loss: 0.6282 - tumor_presence_accuracy: 0.9084 - tumor_presence_auc: 0.9549 - tumor_presence_loss: 0.0662 - tumor_presence_precision: 0.9313 - tumor_presence_recall: 0.9433 - tumor_type_accuracy: 0.5960 - tumor_type_loss: 0.4323 - val_loss: 1.2365 - val_tumor_presence_accuracy: 0.9055 - val_tumor_presence_auc: 0.9529 - val_tumor_presence_loss: 0.0611 - val_tumor_presence_precision: 0.9032 - val_tumor_presence_recall: 0.9733 - val_tumor_type_accuracy: 0.3500 - val_tumor_type_loss: 0.8802 - learning_rate: 0.0010
Epoch 4/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - loss: 0.6281 - tumor_presence_accuracy: 0.9118 - tumor_presence_auc: 0.9644 - tumor_presence_loss: 0.0580 - tumor_presence_precision: 0.9407 - tumor_presence_recall: 0.9383 - tumor_type_accuracy: 0.5895 - tumor_type_loss: 0.4385
Epoch 4: saving model to /kaggle/working/checkpoints/epoch_04.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 180ms/step - loss: 0.6281 - tumor_presence_accuracy: 0.9118 - tumor_presence_auc: 0.9644 - tumor_presence_loss: 0.0580 - tumor_presence_precision: 0.9407 - tumor_presence_recall: 0.9384 - tumor_type_accuracy: 0.5895 - tumor_type_loss: 0.4386 - val_loss: 2.1906 - val_tumor_presence_accuracy: 0.8320 - val_tumor_presence_auc: 0.9439 - val_tumor_presence_loss: 0.1583 - val_tumor_presence_precision: 0.8116 - val_tumor_presence_recall: 0.9988 - val_tumor_type_accuracy: 0.3246 - val_tumor_type_loss: 1.5199 - learning_rate: 0.0010
Epoch 5/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 0.6109 - tumor_presence_accuracy: 0.9323 - tumor_presence_auc: 0.9687 - tumor_presence_loss: 0.0524 - tumor_presence_precision: 0.9510 - tumor_presence_recall: 0.9560 - tumor_type_accuracy: 0.5975 - tumor_type_loss: 0.4296
Epoch 5: saving model to /kaggle/working/checkpoints/epoch_05.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 179ms/step - loss: 0.6108 - tumor_presence_accuracy: 0.9323 - tumor_presence_auc: 0.9687 - tumor_presence_loss: 0.0524 - tumor_presence_precision: 0.9510 - tumor_presence_recall: 0.9560 - tumor_type_accuracy: 0.5975 - tumor_type_loss: 0.4295 - val_loss: 1.2498 - val_tumor_presence_accuracy: 0.9256 - val_tumor_presence_auc: 0.9552 - val_tumor_presence_loss: 0.0606 - val_tumor_presence_precision: 0.9352 - val_tumor_presence_recall: 0.9636 - val_tumor_type_accuracy: 0.4576 - val_tumor_type_loss: 0.9133 - learning_rate: 0.0010
Epoch 6/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 0.5702 - tumor_presence_accuracy: 0.9326 - tumor_presence_auc: 0.9743 - tumor_presence_loss: 0.0485 - tumor_presence_precision: 0.9474 - tumor_presence_recall: 0.9604 - tumor_type_accuracy: 0.6092 - tumor_type_loss: 0.4014
Epoch 6: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.

Epoch 6: saving model to /kaggle/working/checkpoints/epoch_06.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 180ms/step - loss: 0.5702 - tumor_presence_accuracy: 0.9326 - tumor_presence_auc: 0.9743 - tumor_presence_loss: 0.0485 - tumor_presence_precision: 0.9474 - tumor_presence_recall: 0.9604 - tumor_type_accuracy: 0.6091 - tumor_type_loss: 0.4014 - val_loss: 3.5589 - val_tumor_presence_accuracy: 0.5319 - val_tumor_presence_auc: 0.9410 - val_tumor_presence_loss: 0.3320 - val_tumor_presence_precision: 0.9769 - val_tumor_presence_recall: 0.3592 - val_tumor_type_accuracy: 0.2380 - val_tumor_type_loss: 2.4119 - learning_rate: 0.0010
Epoch 7/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 0.5456 - tumor_presence_accuracy: 0.9352 - tumor_presence_auc: 0.9762 - tumor_presence_loss: 0.0466 - tumor_presence_precision: 0.9565 - tumor_presence_recall: 0.9541 - tumor_type_accuracy: 0.6115 - tumor_type_loss: 0.3839
Epoch 7: saving model to /kaggle/working/checkpoints/epoch_07.weights.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

143/143 ━━━━━━━━━━━━━━━━━━━━ 45s 312ms/step - loss: 0.5454 - tumor_presence_accuracy: 0.9352 - tumor_presence_auc: 0.9762 - tumor_presence_loss: 0.0466 - tumor_presence_precision: 0.9565 - tumor_presence_recall: 0.9542 - tumor_type_accuracy: 0.6115 - tumor_type_loss: 0.3837 - val_loss: 0.6238 - val_tumor_presence_accuracy: 0.8058 - val_tumor_presence_auc: 0.9628 - val_tumor_presence_loss: 0.1065 - val_tumor_presence_precision: 0.9808 - val_tumor_presence_recall: 0.7451 - val_tumor_type_accuracy: 0.6010 - val_tumor_type_loss: 0.3871 - learning_rate: 5.0000e-04
Epoch 8/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 0.5061 - tumor_presence_accuracy: 0.9517 - tumor_presence_auc: 0.9859 - tumor_presence_loss: 0.0355 - tumor_presence_precision: 0.9636 - tumor_presence_recall: 0.9703 - tumor_type_accuracy: 0.6144 - tumor_type_loss: 0.3620
Epoch 8: saving model to /kaggle/working/checkpoints/epoch_08.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 179ms/step - loss: 0.5062 - tumor_presence_accuracy: 0.9517 - tumor_presence_auc: 0.9859 - tumor_presence_loss: 0.0355 - tumor_presence_precision: 0.9636 - tumor_presence_recall: 0.9703 - tumor_type_accuracy: 0.6144 - tumor_type_loss: 0.3620 - val_loss: 1.8734 - val_tumor_presence_accuracy: 0.9519 - val_tumor_presence_auc: 0.9848 - val_tumor_presence_loss: 0.0360 - val_tumor_presence_precision: 0.9508 - val_tumor_presence_recall: 0.9842 - val_tumor_type_accuracy: 0.4077 - val_tumor_type_loss: 1.3748 - learning_rate: 5.0000e-04
Epoch 9/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 0.4642 - tumor_presence_accuracy: 0.9503 - tumor_presence_auc: 0.9843 - tumor_presence_loss: 0.0379 - tumor_presence_precision: 0.9602 - tumor_presence_recall: 0.9719 - tumor_type_accuracy: 0.6245 - tumor_type_loss: 0.3280
Epoch 9: saving model to /kaggle/working/checkpoints/epoch_09.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 179ms/step - loss: 0.4644 - tumor_presence_accuracy: 0.9503 - tumor_presence_auc: 0.9843 - tumor_presence_loss: 0.0379 - tumor_presence_precision: 0.9602 - tumor_presence_recall: 0.9720 - tumor_type_accuracy: 0.6244 - tumor_type_loss: 0.3281 - val_loss: 0.8677 - val_tumor_presence_accuracy: 0.9379 - val_tumor_presence_auc: 0.9738 - val_tumor_presence_loss: 0.0477 - val_tumor_presence_precision: 0.9553 - val_tumor_presence_recall: 0.9587 - val_tumor_type_accuracy: 0.5066 - val_tumor_type_loss: 0.6146 - learning_rate: 5.0000e-04
Epoch 10/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 0.4483 - tumor_presence_accuracy: 0.9511 - tumor_presence_auc: 0.9879 - tumor_presence_loss: 0.0350 - tumor_presence_precision: 0.9638 - tumor_presence_recall: 0.9694 - tumor_type_accuracy: 0.6360 - tumor_type_loss: 0.3180
Epoch 10: saving model to /kaggle/working/checkpoints/epoch_10.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 179ms/step - loss: 0.4484 - tumor_presence_accuracy: 0.9511 - tumor_presence_auc: 0.9879 - tumor_presence_loss: 0.0350 - tumor_presence_precision: 0.9637 - tumor_presence_recall: 0.9695 - tumor_type_accuracy: 0.6360 - tumor_type_loss: 0.3180 - val_loss: 1.0017 - val_tumor_presence_accuracy: 0.8486 - val_tumor_presence_auc: 0.9853 - val_tumor_presence_loss: 0.0874 - val_tumor_presence_precision: 0.9895 - val_tumor_presence_recall: 0.7985 - val_tumor_type_accuracy: 0.5031 - val_tumor_type_loss: 0.6818 - learning_rate: 5.0000e-04
Epoch 11/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 0.4649 - tumor_presence_accuracy: 0.9546 - tumor_presence_auc: 0.9868 - tumor_presence_loss: 0.0349 - tumor_presence_precision: 0.9636 - tumor_presence_recall: 0.9741 - tumor_type_accuracy: 0.6196 - tumor_type_loss: 0.3307
Epoch 11: saving model to /kaggle/working/checkpoints/epoch_11.weights.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

143/143 ━━━━━━━━━━━━━━━━━━━━ 98s 683ms/step - loss: 0.4649 - tumor_presence_accuracy: 0.9546 - tumor_presence_auc: 0.9868 - tumor_presence_loss: 0.0349 - tumor_presence_precision: 0.9636 - tumor_presence_recall: 0.9741 - tumor_type_accuracy: 0.6196 - tumor_type_loss: 0.3308 - val_loss: 0.6219 - val_tumor_presence_accuracy: 0.9064 - val_tumor_presence_auc: 0.9753 - val_tumor_presence_loss: 0.0536 - val_tumor_presence_precision: 0.9699 - val_tumor_presence_recall: 0.8981 - val_tumor_type_accuracy: 0.5967 - val_tumor_type_loss: 0.4246 - learning_rate: 5.0000e-04
Epoch 12/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - loss: 0.4696 - tumor_presence_accuracy: 0.9557 - tumor_presence_auc: 0.9885 - tumor_presence_loss: 0.0322 - tumor_presence_precision: 0.9677 - tumor_presence_recall: 0.9714 - tumor_type_accuracy: 0.6206 - tumor_type_loss: 0.3365
Epoch 12: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.

Epoch 12: saving model to /kaggle/working/checkpoints/epoch_12.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 181ms/step - loss: 0.4696 - tumor_presence_accuracy: 0.9557 - tumor_presence_auc: 0.9885 - tumor_presence_loss: 0.0322 - tumor_presence_precision: 0.9677 - tumor_presence_recall: 0.9714 - tumor_type_accuracy: 0.6206 - tumor_type_loss: 0.3364 - val_loss: 2.4570 - val_tumor_presence_accuracy: 0.9195 - val_tumor_presence_auc: 0.9733 - val_tumor_presence_loss: 0.0604 - val_tumor_presence_precision: 0.9058 - val_tumor_presence_recall: 0.9915 - val_tumor_type_accuracy: 0.3395 - val_tumor_type_loss: 1.7967 - learning_rate: 5.0000e-04
Epoch 13/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 0.4360 - tumor_presence_accuracy: 0.9496 - tumor_presence_auc: 0.9869 - tumor_presence_loss: 0.0345 - tumor_presence_precision: 0.9681 - tumor_presence_recall: 0.9623 - tumor_type_accuracy: 0.6330 - tumor_type_loss: 0.3088
Epoch 13: saving model to /kaggle/working/checkpoints/epoch_13.weights.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

143/143 ━━━━━━━━━━━━━━━━━━━━ 87s 609ms/step - loss: 0.4360 - tumor_presence_accuracy: 0.9496 - tumor_presence_auc: 0.9869 - tumor_presence_loss: 0.0345 - tumor_presence_precision: 0.9681 - tumor_presence_recall: 0.9624 - tumor_type_accuracy: 0.6329 - tumor_type_loss: 0.3089 - val_loss: 0.4272 - val_tumor_presence_accuracy: 0.9501 - val_tumor_presence_auc: 0.9897 - val_tumor_presence_loss: 0.0374 - val_tumor_presence_precision: 0.9393 - val_tumor_presence_recall: 0.9951 - val_tumor_type_accuracy: 0.6439 - val_tumor_type_loss: 0.2913 - learning_rate: 2.5000e-04
Epoch 14/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - loss: 0.4246 - tumor_presence_accuracy: 0.9549 - tumor_presence_auc: 0.9905 - tumor_presence_loss: 0.0295 - tumor_presence_precision: 0.9691 - tumor_presence_recall: 0.9691 - tumor_type_accuracy: 0.6340 - tumor_type_loss: 0.3039
Epoch 14: saving model to /kaggle/working/checkpoints/epoch_14.weights.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

143/143 ━━━━━━━━━━━━━━━━━━━━ 49s 341ms/step - loss: 0.4245 - tumor_presence_accuracy: 0.9549 - tumor_presence_auc: 0.9905 - tumor_presence_loss: 0.0295 - tumor_presence_precision: 0.9691 - tumor_presence_recall: 0.9691 - tumor_type_accuracy: 0.6340 - tumor_type_loss: 0.3038 - val_loss: 0.3970 - val_tumor_presence_accuracy: 0.9711 - val_tumor_presence_auc: 0.9939 - val_tumor_presence_loss: 0.0231 - val_tumor_presence_precision: 0.9759 - val_tumor_presence_recall: 0.9842 - val_tumor_type_accuracy: 0.6527 - val_tumor_type_loss: 0.2805 - learning_rate: 2.5000e-04
Epoch 15/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - loss: 0.3932 - tumor_presence_accuracy: 0.9627 - tumor_presence_auc: 0.9904 - tumor_presence_loss: 0.0290 - tumor_presence_precision: 0.9731 - tumor_presence_recall: 0.9754 - tumor_type_accuracy: 0.6331 - tumor_type_loss: 0.2801
Epoch 15: saving model to /kaggle/working/checkpoints/epoch_15.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 181ms/step - loss: 0.3932 - tumor_presence_accuracy: 0.9627 - tumor_presence_auc: 0.9904 - tumor_presence_loss: 0.0290 - tumor_presence_precision: 0.9731 - tumor_presence_recall: 0.9754 - tumor_type_accuracy: 0.6331 - tumor_type_loss: 0.2802 - val_loss: 0.5070 - val_tumor_presence_accuracy: 0.9291 - val_tumor_presence_auc: 0.9894 - val_tumor_presence_loss: 0.0484 - val_tumor_presence_precision: 0.9831 - val_tumor_presence_recall: 0.9175 - val_tumor_type_accuracy: 0.6177 - val_tumor_type_loss: 0.3431 - learning_rate: 2.5000e-04
Epoch 16/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - loss: 0.4009 - tumor_presence_accuracy: 0.9646 - tumor_presence_auc: 0.9859 - tumor_presence_loss: 0.0351 - tumor_presence_precision: 0.9754 - tumor_presence_recall: 0.9757 - tumor_type_accuracy: 0.6398 - tumor_type_loss: 0.2814
Epoch 16: saving model to /kaggle/working/checkpoints/epoch_16.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 181ms/step - loss: 0.4009 - tumor_presence_accuracy: 0.9646 - tumor_presence_auc: 0.9859 - tumor_presence_loss: 0.0351 - tumor_presence_precision: 0.9754 - tumor_presence_recall: 0.9757 - tumor_type_accuracy: 0.6398 - tumor_type_loss: 0.2814 - val_loss: 0.7011 - val_tumor_presence_accuracy: 0.9458 - val_tumor_presence_auc: 0.9917 - val_tumor_presence_loss: 0.0463 - val_tumor_presence_precision: 0.9320 - val_tumor_presence_recall: 0.9976 - val_tumor_type_accuracy: 0.5634 - val_tumor_type_loss: 0.4894 - learning_rate: 2.5000e-04
Epoch 17/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - loss: 0.3806 - tumor_presence_accuracy: 0.9646 - tumor_presence_auc: 0.9914 - tumor_presence_loss: 0.0277 - tumor_presence_precision: 0.9745 - tumor_presence_recall: 0.9767 - tumor_type_accuracy: 0.6424 - tumor_type_loss: 0.2715
Epoch 17: saving model to /kaggle/working/checkpoints/epoch_17.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 181ms/step - loss: 0.3806 - tumor_presence_accuracy: 0.9646 - tumor_presence_auc: 0.9914 - tumor_presence_loss: 0.0276 - tumor_presence_precision: 0.9745 - tumor_presence_recall: 0.9767 - tumor_type_accuracy: 0.6423 - tumor_type_loss: 0.2715 - val_loss: 0.8056 - val_tumor_presence_accuracy: 0.8968 - val_tumor_presence_auc: 0.9804 - val_tumor_presence_loss: 0.0565 - val_tumor_presence_precision: 0.9809 - val_tumor_presence_recall: 0.8738 - val_tumor_type_accuracy: 0.5354 - val_tumor_type_loss: 0.5618 - learning_rate: 2.5000e-04
Epoch 18/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - loss: 0.3741 - tumor_presence_accuracy: 0.9643 - tumor_presence_auc: 0.9924 - tumor_presence_loss: 0.0262 - tumor_presence_precision: 0.9754 - tumor_presence_recall: 0.9755 - tumor_type_accuracy: 0.6447 - tumor_type_loss: 0.2677
Epoch 18: saving model to /kaggle/working/checkpoints/epoch_18.weights.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

143/143 ━━━━━━━━━━━━━━━━━━━━ 47s 328ms/step - loss: 0.3742 - tumor_presence_accuracy: 0.9643 - tumor_presence_auc: 0.9924 - tumor_presence_loss: 0.0262 - tumor_presence_precision: 0.9754 - tumor_presence_recall: 0.9755 - tumor_type_accuracy: 0.6446 - tumor_type_loss: 0.2677 - val_loss: 0.3923 - val_tumor_presence_accuracy: 0.9703 - val_tumor_presence_auc: 0.9932 - val_tumor_presence_loss: 0.0237 - val_tumor_presence_precision: 0.9714 - val_tumor_presence_recall: 0.9879 - val_tumor_type_accuracy: 0.6439 - val_tumor_type_loss: 0.2768 - learning_rate: 2.5000e-04
Epoch 19/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - loss: 0.3719 - tumor_presence_accuracy: 0.9670 - tumor_presence_auc: 0.9930 - tumor_presence_loss: 0.0253 - tumor_presence_precision: 0.9774 - tumor_presence_recall: 0.9773 - tumor_type_accuracy: 0.6544 - tumor_type_loss: 0.2666
Epoch 19: saving model to /kaggle/working/checkpoints/epoch_19.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 180ms/step - loss: 0.3718 - tumor_presence_accuracy: 0.9670 - tumor_presence_auc: 0.9930 - tumor_presence_loss: 0.0253 - tumor_presence_precision: 0.9774 - tumor_presence_recall: 0.9773 - tumor_type_accuracy: 0.6543 - tumor_type_loss: 0.2665 - val_loss: 0.8743 - val_tumor_presence_accuracy: 0.9676 - val_tumor_presence_auc: 0.9886 - val_tumor_presence_loss: 0.0296 - val_tumor_presence_precision: 0.9747 - val_tumor_presence_recall: 0.9806 - val_tumor_type_accuracy: 0.5109 - val_tumor_type_loss: 0.6326 - learning_rate: 2.5000e-04
Epoch 20/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 0.3619 - tumor_presence_accuracy: 0.9645 - tumor_presence_auc: 0.9928 - tumor_presence_loss: 0.0258 - tumor_presence_precision: 0.9706 - tumor_presence_recall: 0.9808 - tumor_type_accuracy: 0.6412 - tumor_type_loss: 0.2585
Epoch 20: saving model to /kaggle/working/checkpoints/epoch_20.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 180ms/step - loss: 0.3619 - tumor_presence_accuracy: 0.9646 - tumor_presence_auc: 0.9928 - tumor_presence_loss: 0.0258 - tumor_presence_precision: 0.9706 - tumor_presence_recall: 0.9808 - tumor_type_accuracy: 0.6412 - tumor_type_loss: 0.2585 - val_loss: 0.4929 - val_tumor_presence_accuracy: 0.9151 - val_tumor_presence_auc: 0.9853 - val_tumor_presence_loss: 0.0556 - val_tumor_presence_precision: 0.9815 - val_tumor_presence_recall: 0.8993 - val_tumor_type_accuracy: 0.6212 - val_tumor_type_loss: 0.3279 - learning_rate: 2.5000e-04
Epoch 21/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - loss: 0.3559 - tumor_presence_accuracy: 0.9672 - tumor_presence_auc: 0.9922 - tumor_presence_loss: 0.0265 - tumor_presence_precision: 0.9777 - tumor_presence_recall: 0.9774 - tumor_type_accuracy: 0.6567 - tumor_type_loss: 0.2534
Epoch 21: saving model to /kaggle/working/checkpoints/epoch_21.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 180ms/step - loss: 0.3559 - tumor_presence_accuracy: 0.9672 - tumor_presence_auc: 0.9922 - tumor_presence_loss: 0.0265 - tumor_presence_precision: 0.9777 - tumor_presence_recall: 0.9775 - tumor_type_accuracy: 0.6566 - tumor_type_loss: 0.2534 - val_loss: 0.9063 - val_tumor_presence_accuracy: 0.9029 - val_tumor_presence_auc: 0.9813 - val_tumor_presence_loss: 0.0612 - val_tumor_presence_precision: 0.9864 - val_tumor_presence_recall: 0.8774 - val_tumor_type_accuracy: 0.5171 - val_tumor_type_loss: 0.6324 - learning_rate: 2.5000e-04
Epoch 22/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 0.3577 - tumor_presence_accuracy: 0.9723 - tumor_presence_auc: 0.9946 - tumor_presence_loss: 0.0220 - tumor_presence_precision: 0.9810 - tumor_presence_recall: 0.9808 - tumor_type_accuracy: 0.6498 - tumor_type_loss: 0.2582
Epoch 22: saving model to /kaggle/working/checkpoints/epoch_22.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 180ms/step - loss: 0.3576 - tumor_presence_accuracy: 0.9723 - tumor_presence_auc: 0.9946 - tumor_presence_loss: 0.0220 - tumor_presence_precision: 0.9810 - tumor_presence_recall: 0.9808 - tumor_type_accuracy: 0.6498 - tumor_type_loss: 0.2581 - val_loss: 1.0738 - val_tumor_presence_accuracy: 0.9536 - val_tumor_presence_auc: 0.9910 - val_tumor_presence_loss: 0.0382 - val_tumor_presence_precision: 0.9457 - val_tumor_presence_recall: 0.9927 - val_tumor_type_accuracy: 0.4978 - val_tumor_type_loss: 0.7766 - learning_rate: 2.5000e-04
Epoch 23/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 0.3492 - tumor_presence_accuracy: 0.9685 - tumor_presence_auc: 0.9927 - tumor_presence_loss: 0.0250 - tumor_presence_precision: 0.9777 - tumor_presence_recall: 0.9789 - tumor_type_accuracy: 0.6480 - tumor_type_loss: 0.2494
Epoch 23: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.

Epoch 23: saving model to /kaggle/working/checkpoints/epoch_23.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 180ms/step - loss: 0.3493 - tumor_presence_accuracy: 0.9685 - tumor_presence_auc: 0.9927 - tumor_presence_loss: 0.0250 - tumor_presence_precision: 0.9777 - tumor_presence_recall: 0.9789 - tumor_type_accuracy: 0.6480 - tumor_type_loss: 0.2495 - val_loss: 2.0566 - val_tumor_presence_accuracy: 0.9563 - val_tumor_presence_auc: 0.9871 - val_tumor_presence_loss: 0.0369 - val_tumor_presence_precision: 0.9825 - val_tumor_presence_recall: 0.9563 - val_tumor_type_accuracy: 0.3080 - val_tumor_type_loss: 1.5160 - learning_rate: 2.5000e-04
Epoch 24/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - loss: 0.3558 - tumor_presence_accuracy: 0.9653 - tumor_presence_auc: 0.9947 - tumor_presence_loss: 0.0226 - tumor_presence_precision: 0.9806 - tumor_presence_recall: 0.9717 - tumor_type_accuracy: 0.6532 - tumor_type_loss: 0.2563
Epoch 24: saving model to /kaggle/working/checkpoints/epoch_24.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 181ms/step - loss: 0.3557 - tumor_presence_accuracy: 0.9653 - tumor_presence_auc: 0.9947 - tumor_presence_loss: 0.0226 - tumor_presence_precision: 0.9806 - tumor_presence_recall: 0.9718 - tumor_type_accuracy: 0.6532 - tumor_type_loss: 0.2563 - val_loss: 0.5123 - val_tumor_presence_accuracy: 0.9379 - val_tumor_presence_auc: 0.9937 - val_tumor_presence_loss: 0.0386 - val_tumor_presence_precision: 0.9934 - val_tumor_presence_recall: 0.9199 - val_tumor_type_accuracy: 0.5976 - val_tumor_type_loss: 0.3568 - learning_rate: 1.2500e-04
Epoch 25/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 0.3240 - tumor_presence_accuracy: 0.9697 - tumor_presence_auc: 0.9944 - tumor_presence_loss: 0.0227 - tumor_presence_precision: 0.9816 - tumor_presence_recall: 0.9765 - tumor_type_accuracy: 0.6523 - tumor_type_loss: 0.2318
Epoch 25: saving model to /kaggle/working/checkpoints/epoch_25.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 179ms/step - loss: 0.3240 - tumor_presence_accuracy: 0.9697 - tumor_presence_auc: 0.9944 - tumor_presence_loss: 0.0227 - tumor_presence_precision: 0.9816 - tumor_presence_recall: 0.9765 - tumor_type_accuracy: 0.6523 - tumor_type_loss: 0.2318 - val_loss: 0.5163 - val_tumor_presence_accuracy: 0.9641 - val_tumor_presence_auc: 0.9936 - val_tumor_presence_loss: 0.0247 - val_tumor_presence_precision: 0.9689 - val_tumor_presence_recall: 0.9818 - val_tumor_type_accuracy: 0.5958 - val_tumor_type_loss: 0.3708 - learning_rate: 1.2500e-04
Epoch 26/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 0.3164 - tumor_presence_accuracy: 0.9667 - tumor_presence_auc: 0.9944 - tumor_presence_loss: 0.0228 - tumor_presence_precision: 0.9768 - tumor_presence_recall: 0.9771 - tumor_type_accuracy: 0.6515 - tumor_type_loss: 0.2258
Epoch 26: saving model to /kaggle/working/checkpoints/epoch_26.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 179ms/step - loss: 0.3164 - tumor_presence_accuracy: 0.9667 - tumor_presence_auc: 0.9944 - tumor_presence_loss: 0.0228 - tumor_presence_precision: 0.9768 - tumor_presence_recall: 0.9771 - tumor_type_accuracy: 0.6515 - tumor_type_loss: 0.2258 - val_loss: 0.6861 - val_tumor_presence_accuracy: 0.9536 - val_tumor_presence_auc: 0.9931 - val_tumor_presence_loss: 0.0304 - val_tumor_presence_precision: 0.9898 - val_tumor_presence_recall: 0.9454 - val_tumor_type_accuracy: 0.5958 - val_tumor_type_loss: 0.4897 - learning_rate: 1.2500e-04
Epoch 27/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - loss: 0.3423 - tumor_presence_accuracy: 0.9711 - tumor_presence_auc: 0.9957 - tumor_presence_loss: 0.0201 - tumor_presence_precision: 0.9788 - tumor_presence_recall: 0.9816 - tumor_type_accuracy: 0.6558 - tumor_type_loss: 0.2479
Epoch 27: saving model to /kaggle/working/checkpoints/epoch_27.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 180ms/step - loss: 0.3423 - tumor_presence_accuracy: 0.9711 - tumor_presence_auc: 0.9957 - tumor_presence_loss: 0.0201 - tumor_presence_precision: 0.9788 - tumor_presence_recall: 0.9816 - tumor_type_accuracy: 0.6557 - tumor_type_loss: 0.2479 - val_loss: 0.4180 - val_tumor_presence_accuracy: 0.9720 - val_tumor_presence_auc: 0.9952 - val_tumor_presence_loss: 0.0197 - val_tumor_presence_precision: 0.9760 - val_tumor_presence_recall: 0.9854 - val_tumor_type_accuracy: 0.6229 - val_tumor_type_loss: 0.2986 - learning_rate: 1.2500e-04
Epoch 28/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 0.3178 - tumor_presence_accuracy: 0.9737 - tumor_presence_auc: 0.9942 - tumor_presence_loss: 0.0221 - tumor_presence_precision: 0.9845 - tumor_presence_recall: 0.9792 - tumor_type_accuracy: 0.6601 - tumor_type_loss: 0.2274
Epoch 28: saving model to /kaggle/working/checkpoints/epoch_28.weights.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

143/143 ━━━━━━━━━━━━━━━━━━━━ 90s 626ms/step - loss: 0.3178 - tumor_presence_accuracy: 0.9737 - tumor_presence_auc: 0.9942 - tumor_presence_loss: 0.0221 - tumor_presence_precision: 0.9845 - tumor_presence_recall: 0.9792 - tumor_type_accuracy: 0.6601 - tumor_type_loss: 0.2275 - val_loss: 0.3417 - val_tumor_presence_accuracy: 0.9738 - val_tumor_presence_auc: 0.9944 - val_tumor_presence_loss: 0.0209 - val_tumor_presence_precision: 0.9760 - val_tumor_presence_recall: 0.9879 - val_tumor_type_accuracy: 0.6544 - val_tumor_type_loss: 0.2401 - learning_rate: 1.2500e-04
Epoch 29/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 0.3417 - tumor_presence_accuracy: 0.9712 - tumor_presence_auc: 0.9922 - tumor_presence_loss: 0.0258 - tumor_presence_precision: 0.9827 - tumor_presence_recall: 0.9779 - tumor_type_accuracy: 0.6572 - tumor_type_loss: 0.2430
Epoch 29: saving model to /kaggle/working/checkpoints/epoch_29.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 180ms/step - loss: 0.3415 - tumor_presence_accuracy: 0.9712 - tumor_presence_auc: 0.9922 - tumor_presence_loss: 0.0258 - tumor_presence_precision: 0.9827 - tumor_presence_recall: 0.9779 - tumor_type_accuracy: 0.6572 - tumor_type_loss: 0.2428 - val_loss: 0.4873 - val_tumor_presence_accuracy: 0.9563 - val_tumor_presence_auc: 0.9933 - val_tumor_presence_loss: 0.0286 - val_tumor_presence_precision: 0.9874 - val_tumor_presence_recall: 0.9515 - val_tumor_type_accuracy: 0.6063 - val_tumor_type_loss: 0.3449 - learning_rate: 1.2500e-04
Epoch 30/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 0.3148 - tumor_presence_accuracy: 0.9704 - tumor_presence_auc: 0.9951 - tumor_presence_loss: 0.0214 - tumor_presence_precision: 0.9837 - tumor_presence_recall: 0.9756 - tumor_type_accuracy: 0.6615 - tumor_type_loss: 0.2256
Epoch 30: saving model to /kaggle/working/checkpoints/epoch_30.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 180ms/step - loss: 0.3147 - tumor_presence_accuracy: 0.9704 - tumor_presence_auc: 0.9952 - tumor_presence_loss: 0.0214 - tumor_presence_precision: 0.9837 - tumor_presence_recall: 0.9756 - tumor_type_accuracy: 0.6615 - tumor_type_loss: 0.2256 - val_loss: 0.3535 - val_tumor_presence_accuracy: 0.9615 - val_tumor_presence_auc: 0.9947 - val_tumor_presence_loss: 0.0271 - val_tumor_presence_precision: 0.9937 - val_tumor_presence_recall: 0.9527 - val_tumor_type_accuracy: 0.6570 - val_tumor_type_loss: 0.2446 - learning_rate: 1.2500e-04
Epoch 31/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - loss: 0.2988 - tumor_presence_accuracy: 0.9736 - tumor_presence_auc: 0.9953 - tumor_presence_loss: 0.0205 - tumor_presence_precision: 0.9841 - tumor_presence_recall: 0.9795 - tumor_type_accuracy: 0.6669 - tumor_type_loss: 0.2141
Epoch 31: saving model to /kaggle/working/checkpoints/epoch_31.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 180ms/step - loss: 0.2988 - tumor_presence_accuracy: 0.9736 - tumor_presence_auc: 0.9953 - tumor_presence_loss: 0.0205 - tumor_presence_precision: 0.9841 - tumor_presence_recall: 0.9795 - tumor_type_accuracy: 0.6669 - tumor_type_loss: 0.2141 - val_loss: 0.3947 - val_tumor_presence_accuracy: 0.9755 - val_tumor_presence_auc: 0.9943 - val_tumor_presence_loss: 0.0218 - val_tumor_presence_precision: 0.9889 - val_tumor_presence_recall: 0.9769 - val_tumor_type_accuracy: 0.6439 - val_tumor_type_loss: 0.2791 - learning_rate: 1.2500e-04
Epoch 32/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 0.3082 - tumor_presence_accuracy: 0.9734 - tumor_presence_auc: 0.9946 - tumor_presence_loss: 0.0212 - tumor_presence_precision: 0.9822 - tumor_presence_recall: 0.9812 - tumor_type_accuracy: 0.6596 - tumor_type_loss: 0.2208
Epoch 32: saving model to /kaggle/working/checkpoints/epoch_32.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 180ms/step - loss: 0.3082 - tumor_presence_accuracy: 0.9735 - tumor_presence_auc: 0.9947 - tumor_presence_loss: 0.0212 - tumor_presence_precision: 0.9822 - tumor_presence_recall: 0.9812 - tumor_type_accuracy: 0.6596 - tumor_type_loss: 0.2207 - val_loss: 0.4552 - val_tumor_presence_accuracy: 0.9720 - val_tumor_presence_auc: 0.9948 - val_tumor_presence_loss: 0.0221 - val_tumor_presence_precision: 0.9877 - val_tumor_presence_recall: 0.9733 - val_tumor_type_accuracy: 0.6334 - val_tumor_type_loss: 0.3231 - learning_rate: 1.2500e-04
Epoch 33/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 0.2993 - tumor_presence_accuracy: 0.9719 - tumor_presence_auc: 0.9952 - tumor_presence_loss: 0.0212 - tumor_presence_precision: 0.9825 - tumor_presence_recall: 0.9785 - tumor_type_accuracy: 0.6566 - tumor_type_loss: 0.2139
Epoch 33: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.

Epoch 33: saving model to /kaggle/working/checkpoints/epoch_33.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 179ms/step - loss: 0.2992 - tumor_presence_accuracy: 0.9719 - tumor_presence_auc: 0.9952 - tumor_presence_loss: 0.0212 - tumor_presence_precision: 0.9825 - tumor_presence_recall: 0.9785 - tumor_type_accuracy: 0.6567 - tumor_type_loss: 0.2139 - val_loss: 0.4108 - val_tumor_presence_accuracy: 0.9703 - val_tumor_presence_auc: 0.9947 - val_tumor_presence_loss: 0.0229 - val_tumor_presence_precision: 0.9841 - val_tumor_presence_recall: 0.9745 - val_tumor_type_accuracy: 0.6413 - val_tumor_type_loss: 0.2901 - learning_rate: 1.2500e-04
Epoch 34/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 0.2878 - tumor_presence_accuracy: 0.9742 - tumor_presence_auc: 0.9965 - tumor_presence_loss: 0.0182 - tumor_presence_precision: 0.9873 - tumor_presence_recall: 0.9774 - tumor_type_accuracy: 0.6682 - tumor_type_loss: 0.2073
Epoch 34: saving model to /kaggle/working/checkpoints/epoch_34.weights.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

143/143 ━━━━━━━━━━━━━━━━━━━━ 71s 494ms/step - loss: 0.2878 - tumor_presence_accuracy: 0.9742 - tumor_presence_auc: 0.9965 - tumor_presence_loss: 0.0182 - tumor_presence_precision: 0.9873 - tumor_presence_recall: 0.9774 - tumor_type_accuracy: 0.6681 - tumor_type_loss: 0.2073 - val_loss: 0.3316 - val_tumor_presence_accuracy: 0.9799 - val_tumor_presence_auc: 0.9953 - val_tumor_presence_loss: 0.0187 - val_tumor_presence_precision: 0.9855 - val_tumor_presence_recall: 0.9867 - val_tumor_type_accuracy: 0.6448 - val_tumor_type_loss: 0.2351 - learning_rate: 6.2500e-05
Epoch 35/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 0.2842 - tumor_presence_accuracy: 0.9679 - tumor_presence_auc: 0.9952 - tumor_presence_loss: 0.0213 - tumor_presence_precision: 0.9755 - tumor_presence_recall: 0.9799 - tumor_type_accuracy: 0.6619 - tumor_type_loss: 0.2022
Epoch 35: saving model to /kaggle/working/checkpoints/epoch_35.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 180ms/step - loss: 0.2842 - tumor_presence_accuracy: 0.9679 - tumor_presence_auc: 0.9952 - tumor_presence_loss: 0.0213 - tumor_presence_precision: 0.9756 - tumor_presence_recall: 0.9799 - tumor_type_accuracy: 0.6620 - tumor_type_loss: 0.2022 - val_loss: 0.3696 - val_tumor_presence_accuracy: 0.9808 - val_tumor_presence_auc: 0.9956 - val_tumor_presence_loss: 0.0184 - val_tumor_presence_precision: 0.9878 - val_tumor_presence_recall: 0.9854 - val_tumor_type_accuracy: 0.6352 - val_tumor_type_loss: 0.2651 - learning_rate: 6.2500e-05
Epoch 36/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 0.2678 - tumor_presence_accuracy: 0.9786 - tumor_presence_auc: 0.9962 - tumor_presence_loss: 0.0186 - tumor_presence_precision: 0.9855 - tumor_presence_recall: 0.9850 - tumor_type_accuracy: 0.6744 - tumor_type_loss: 0.1917
Epoch 36: saving model to /kaggle/working/checkpoints/epoch_36.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 180ms/step - loss: 0.2678 - tumor_presence_accuracy: 0.9786 - tumor_presence_auc: 0.9962 - tumor_presence_loss: 0.0186 - tumor_presence_precision: 0.9855 - tumor_presence_recall: 0.9850 - tumor_type_accuracy: 0.6743 - tumor_type_loss: 0.1917 - val_loss: 0.3886 - val_tumor_presence_accuracy: 0.9790 - val_tumor_presence_auc: 0.9959 - val_tumor_presence_loss: 0.0179 - val_tumor_presence_precision: 0.9808 - val_tumor_presence_recall: 0.9903 - val_tumor_type_accuracy: 0.6299 - val_tumor_type_loss: 0.2794 - learning_rate: 6.2500e-05
Epoch 37/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 0.2992 - tumor_presence_accuracy: 0.9755 - tumor_presence_auc: 0.9957 - tumor_presence_loss: 0.0193 - tumor_presence_precision: 0.9853 - tumor_presence_recall: 0.9808 - tumor_type_accuracy: 0.6543 - tumor_type_loss: 0.2153
Epoch 37: saving model to /kaggle/working/checkpoints/epoch_37.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 179ms/step - loss: 0.2991 - tumor_presence_accuracy: 0.9755 - tumor_presence_auc: 0.9957 - tumor_presence_loss: 0.0193 - tumor_presence_precision: 0.9853 - tumor_presence_recall: 0.9808 - tumor_type_accuracy: 0.6543 - tumor_type_loss: 0.2152 - val_loss: 0.3494 - val_tumor_presence_accuracy: 0.9738 - val_tumor_presence_auc: 0.9951 - val_tumor_presence_loss: 0.0195 - val_tumor_presence_precision: 0.9901 - val_tumor_presence_recall: 0.9733 - val_tumor_type_accuracy: 0.6422 - val_tumor_type_loss: 0.2480 - learning_rate: 6.2500e-05
Epoch 38/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 0.2809 - tumor_presence_accuracy: 0.9779 - tumor_presence_auc: 0.9955 - tumor_presence_loss: 0.0199 - tumor_presence_precision: 0.9878 - tumor_presence_recall: 0.9818 - tumor_type_accuracy: 0.6662 - tumor_type_loss: 0.2007
Epoch 38: saving model to /kaggle/working/checkpoints/epoch_38.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 180ms/step - loss: 0.2808 - tumor_presence_accuracy: 0.9779 - tumor_presence_auc: 0.9955 - tumor_presence_loss: 0.0199 - tumor_presence_precision: 0.9878 - tumor_presence_recall: 0.9818 - tumor_type_accuracy: 0.6662 - tumor_type_loss: 0.2007 - val_loss: 0.3805 - val_tumor_presence_accuracy: 0.9773 - val_tumor_presence_auc: 0.9956 - val_tumor_presence_loss: 0.0181 - val_tumor_presence_precision: 0.9890 - val_tumor_presence_recall: 0.9794 - val_tumor_type_accuracy: 0.6387 - val_tumor_type_loss: 0.2710 - learning_rate: 6.2500e-05
Epoch 39/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 0.2850 - tumor_presence_accuracy: 0.9704 - tumor_presence_auc: 0.9958 - tumor_presence_loss: 0.0200 - tumor_presence_precision: 0.9850 - tumor_presence_recall: 0.9744 - tumor_type_accuracy: 0.6756 - tumor_type_loss: 0.2039
Epoch 39: ReduceLROnPlateau reducing learning rate to 3.125000148429535e-05.

Epoch 39: saving model to /kaggle/working/checkpoints/epoch_39.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 180ms/step - loss: 0.2850 - tumor_presence_accuracy: 0.9704 - tumor_presence_auc: 0.9958 - tumor_presence_loss: 0.0200 - tumor_presence_precision: 0.9850 - tumor_presence_recall: 0.9744 - tumor_type_accuracy: 0.6755 - tumor_type_loss: 0.2038 - val_loss: 0.3714 - val_tumor_presence_accuracy: 0.9773 - val_tumor_presence_auc: 0.9951 - val_tumor_presence_loss: 0.0193 - val_tumor_presence_precision: 0.9866 - val_tumor_presence_recall: 0.9818 - val_tumor_type_accuracy: 0.6483 - val_tumor_type_loss: 0.2632 - learning_rate: 6.2500e-05
Epoch 40/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 0.2784 - tumor_presence_accuracy: 0.9694 - tumor_presence_auc: 0.9943 - tumor_presence_loss: 0.0228 - tumor_presence_precision: 0.9789 - tumor_presence_recall: 0.9792 - tumor_type_accuracy: 0.6728 - tumor_type_loss: 0.1966
Epoch 40: saving model to /kaggle/working/checkpoints/epoch_40.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 180ms/step - loss: 0.2784 - tumor_presence_accuracy: 0.9695 - tumor_presence_auc: 0.9943 - tumor_presence_loss: 0.0227 - tumor_presence_precision: 0.9789 - tumor_presence_recall: 0.9793 - tumor_type_accuracy: 0.6727 - tumor_type_loss: 0.1966 - val_loss: 0.3488 - val_tumor_presence_accuracy: 0.9790 - val_tumor_presence_auc: 0.9955 - val_tumor_presence_loss: 0.0189 - val_tumor_presence_precision: 0.9878 - val_tumor_presence_recall: 0.9830 - val_tumor_type_accuracy: 0.6387 - val_tumor_type_loss: 0.2481 - learning_rate: 3.1250e-05
Epoch 41/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 0.2765 - tumor_presence_accuracy: 0.9733 - tumor_presence_auc: 0.9964 - tumor_presence_loss: 0.0185 - tumor_presence_precision: 0.9841 - tumor_presence_recall: 0.9790 - tumor_type_accuracy: 0.6706 - tumor_type_loss: 0.1985
Epoch 41: saving model to /kaggle/working/checkpoints/epoch_41.weights.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

143/143 ━━━━━━━━━━━━━━━━━━━━ 69s 484ms/step - loss: 0.2765 - tumor_presence_accuracy: 0.9733 - tumor_presence_auc: 0.9964 - tumor_presence_loss: 0.0185 - tumor_presence_precision: 0.9841 - tumor_presence_recall: 0.9790 - tumor_type_accuracy: 0.6706 - tumor_type_loss: 0.1985 - val_loss: 0.3252 - val_tumor_presence_accuracy: 0.9790 - val_tumor_presence_auc: 0.9956 - val_tumor_presence_loss: 0.0185 - val_tumor_presence_precision: 0.9902 - val_tumor_presence_recall: 0.9806 - val_tumor_type_accuracy: 0.6465 - val_tumor_type_loss: 0.2304 - learning_rate: 3.1250e-05
Epoch 42/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 0.2858 - tumor_presence_accuracy: 0.9785 - tumor_presence_auc: 0.9969 - tumor_presence_loss: 0.0168 - tumor_presence_precision: 0.9870 - tumor_presence_recall: 0.9834 - tumor_type_accuracy: 0.6599 - tumor_type_loss: 0.2070
Epoch 42: saving model to /kaggle/working/checkpoints/epoch_42.weights.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

143/143 ━━━━━━━━━━━━━━━━━━━━ 58s 405ms/step - loss: 0.2857 - tumor_presence_accuracy: 0.9785 - tumor_presence_auc: 0.9969 - tumor_presence_loss: 0.0168 - tumor_presence_precision: 0.9870 - tumor_presence_recall: 0.9834 - tumor_type_accuracy: 0.6599 - tumor_type_loss: 0.2069 - val_loss: 0.3004 - val_tumor_presence_accuracy: 0.9808 - val_tumor_presence_auc: 0.9955 - val_tumor_presence_loss: 0.0185 - val_tumor_presence_precision: 0.9890 - val_tumor_presence_recall: 0.9842 - val_tumor_type_accuracy: 0.6579 - val_tumor_type_loss: 0.2116 - learning_rate: 3.1250e-05
Epoch 43/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 0.2645 - tumor_presence_accuracy: 0.9739 - tumor_presence_auc: 0.9963 - tumor_presence_loss: 0.0185 - tumor_presence_precision: 0.9869 - tumor_presence_recall: 0.9770 - tumor_type_accuracy: 0.6655 - tumor_type_loss: 0.1892
Epoch 43: saving model to /kaggle/working/checkpoints/epoch_43.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 180ms/step - loss: 0.2645 - tumor_presence_accuracy: 0.9739 - tumor_presence_auc: 0.9963 - tumor_presence_loss: 0.0185 - tumor_presence_precision: 0.9869 - tumor_presence_recall: 0.9770 - tumor_type_accuracy: 0.6655 - tumor_type_loss: 0.1892 - val_loss: 0.3677 - val_tumor_presence_accuracy: 0.9816 - val_tumor_presence_auc: 0.9956 - val_tumor_presence_loss: 0.0178 - val_tumor_presence_precision: 0.9890 - val_tumor_presence_recall: 0.9854 - val_tumor_type_accuracy: 0.6343 - val_tumor_type_loss: 0.2638 - learning_rate: 3.1250e-05
Epoch 44/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 0.2617 - tumor_presence_accuracy: 0.9726 - tumor_presence_auc: 0.9957 - tumor_presence_loss: 0.0196 - tumor_presence_precision: 0.9838 - tumor_presence_recall: 0.9785 - tumor_type_accuracy: 0.6679 - tumor_type_loss: 0.1862
Epoch 44: saving model to /kaggle/working/checkpoints/epoch_44.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 180ms/step - loss: 0.2617 - tumor_presence_accuracy: 0.9727 - tumor_presence_auc: 0.9957 - tumor_presence_loss: 0.0196 - tumor_presence_precision: 0.9838 - tumor_presence_recall: 0.9785 - tumor_type_accuracy: 0.6679 - tumor_type_loss: 0.1863 - val_loss: 0.3010 - val_tumor_presence_accuracy: 0.9808 - val_tumor_presence_auc: 0.9955 - val_tumor_presence_loss: 0.0189 - val_tumor_presence_precision: 0.9878 - val_tumor_presence_recall: 0.9854 - val_tumor_type_accuracy: 0.6597 - val_tumor_type_loss: 0.2119 - learning_rate: 3.1250e-05
Epoch 45/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 0.2590 - tumor_presence_accuracy: 0.9707 - tumor_presence_auc: 0.9962 - tumor_presence_loss: 0.0187 - tumor_presence_precision: 0.9803 - tumor_presence_recall: 0.9792 - tumor_type_accuracy: 0.6662 - tumor_type_loss: 0.1849
Epoch 45: saving model to /kaggle/working/checkpoints/epoch_45.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 179ms/step - loss: 0.2590 - tumor_presence_accuracy: 0.9707 - tumor_presence_auc: 0.9962 - tumor_presence_loss: 0.0187 - tumor_presence_precision: 0.9804 - tumor_presence_recall: 0.9792 - tumor_type_accuracy: 0.6662 - tumor_type_loss: 0.1848 - val_loss: 0.3353 - val_tumor_presence_accuracy: 0.9773 - val_tumor_presence_auc: 0.9958 - val_tumor_presence_loss: 0.0187 - val_tumor_presence_precision: 0.9902 - val_tumor_presence_recall: 0.9782 - val_tumor_type_accuracy: 0.6439 - val_tumor_type_loss: 0.2379 - learning_rate: 3.1250e-05
Epoch 46/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - loss: 0.2640 - tumor_presence_accuracy: 0.9723 - tumor_presence_auc: 0.9950 - tumor_presence_loss: 0.0212 - tumor_presence_precision: 0.9865 - tumor_presence_recall: 0.9754 - tumor_type_accuracy: 0.6702 - tumor_type_loss: 0.1868
Epoch 46: saving model to /kaggle/working/checkpoints/epoch_46.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 178ms/step - loss: 0.2639 - tumor_presence_accuracy: 0.9723 - tumor_presence_auc: 0.9950 - tumor_presence_loss: 0.0212 - tumor_presence_precision: 0.9865 - tumor_presence_recall: 0.9754 - tumor_type_accuracy: 0.6702 - tumor_type_loss: 0.1867 - val_loss: 0.3110 - val_tumor_presence_accuracy: 0.9790 - val_tumor_presence_auc: 0.9955 - val_tumor_presence_loss: 0.0186 - val_tumor_presence_precision: 0.9854 - val_tumor_presence_recall: 0.9854 - val_tumor_type_accuracy: 0.6500 - val_tumor_type_loss: 0.2197 - learning_rate: 3.1250e-05
Epoch 47/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 0.2455 - tumor_presence_accuracy: 0.9772 - tumor_presence_auc: 0.9965 - tumor_presence_loss: 0.0178 - tumor_presence_precision: 0.9898 - tumor_presence_recall: 0.9788 - tumor_type_accuracy: 0.6769 - tumor_type_loss: 0.1752
Epoch 47: ReduceLROnPlateau reducing learning rate to 1.5625000742147677e-05.

Epoch 47: saving model to /kaggle/working/checkpoints/epoch_47.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 179ms/step - loss: 0.2457 - tumor_presence_accuracy: 0.9772 - tumor_presence_auc: 0.9965 - tumor_presence_loss: 0.0178 - tumor_presence_precision: 0.9898 - tumor_presence_recall: 0.9788 - tumor_type_accuracy: 0.6768 - tumor_type_loss: 0.1753 - val_loss: 0.3332 - val_tumor_presence_accuracy: 0.9799 - val_tumor_presence_auc: 0.9951 - val_tumor_presence_loss: 0.0210 - val_tumor_presence_precision: 0.9831 - val_tumor_presence_recall: 0.9891 - val_tumor_type_accuracy: 0.6535 - val_tumor_type_loss: 0.2345 - learning_rate: 3.1250e-05
Epoch 48/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - loss: 0.2489 - tumor_presence_accuracy: 0.9774 - tumor_presence_auc: 0.9964 - tumor_presence_loss: 0.0181 - tumor_presence_precision: 0.9890 - tumor_presence_recall: 0.9797 - tumor_type_accuracy: 0.6701 - tumor_type_loss: 0.1776
Epoch 48: saving model to /kaggle/working/checkpoints/epoch_48.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 180ms/step - loss: 0.2490 - tumor_presence_accuracy: 0.9774 - tumor_presence_auc: 0.9964 - tumor_presence_loss: 0.0181 - tumor_presence_precision: 0.9890 - tumor_presence_recall: 0.9797 - tumor_type_accuracy: 0.6701 - tumor_type_loss: 0.1776 - val_loss: 0.3322 - val_tumor_presence_accuracy: 0.9808 - val_tumor_presence_auc: 0.9957 - val_tumor_presence_loss: 0.0187 - val_tumor_presence_precision: 0.9878 - val_tumor_presence_recall: 0.9854 - val_tumor_type_accuracy: 0.6439 - val_tumor_type_loss: 0.2357 - learning_rate: 1.5625e-05
Epoch 49/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 0.2489 - tumor_presence_accuracy: 0.9750 - tumor_presence_auc: 0.9962 - tumor_presence_loss: 0.0186 - tumor_presence_precision: 0.9856 - tumor_presence_recall: 0.9797 - tumor_type_accuracy: 0.6705 - tumor_type_loss: 0.1772
Epoch 49: saving model to /kaggle/working/checkpoints/epoch_49.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 180ms/step - loss: 0.2489 - tumor_presence_accuracy: 0.9750 - tumor_presence_auc: 0.9962 - tumor_presence_loss: 0.0186 - tumor_presence_precision: 0.9856 - tumor_presence_recall: 0.9797 - tumor_type_accuracy: 0.6705 - tumor_type_loss: 0.1772 - val_loss: 0.3675 - val_tumor_presence_accuracy: 0.9799 - val_tumor_presence_auc: 0.9957 - val_tumor_presence_loss: 0.0188 - val_tumor_presence_precision: 0.9890 - val_tumor_presence_recall: 0.9830 - val_tumor_type_accuracy: 0.6404 - val_tumor_type_loss: 0.2619 - learning_rate: 1.5625e-05
Epoch 50/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - loss: 0.2386 - tumor_presence_accuracy: 0.9815 - tumor_presence_auc: 0.9969 - tumor_presence_loss: 0.0168 - tumor_presence_precision: 0.9883 - tumor_presence_recall: 0.9859 - tumor_type_accuracy: 0.6667 - tumor_type_loss: 0.1707
Epoch 50: saving model to /kaggle/working/checkpoints/epoch_50.weights.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

143/143 ━━━━━━━━━━━━━━━━━━━━ 78s 542ms/step - loss: 0.2387 - tumor_presence_accuracy: 0.9814 - tumor_presence_auc: 0.9969 - tumor_presence_loss: 0.0168 - tumor_presence_precision: 0.9883 - tumor_presence_recall: 0.9859 - tumor_type_accuracy: 0.6667 - tumor_type_loss: 0.1707 - val_loss: 0.2990 - val_tumor_presence_accuracy: 0.9825 - val_tumor_presence_auc: 0.9958 - val_tumor_presence_loss: 0.0179 - val_tumor_presence_precision: 0.9902 - val_tumor_presence_recall: 0.9854 - val_tumor_type_accuracy: 0.6544 - val_tumor_type_loss: 0.2174 - learning_rate: 1.5625e-05
Epoch 51/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 0.2618 - tumor_presence_accuracy: 0.9778 - tumor_presence_auc: 0.9970 - tumor_presence_loss: 0.0164 - tumor_presence_precision: 0.9849 - tumor_presence_recall: 0.9844 - tumor_type_accuracy: 0.6672 - tumor_type_loss: 0.1887
Epoch 51: saving model to /kaggle/working/checkpoints/epoch_51.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 179ms/step - loss: 0.2617 - tumor_presence_accuracy: 0.9778 - tumor_presence_auc: 0.9970 - tumor_presence_loss: 0.0164 - tumor_presence_precision: 0.9849 - tumor_presence_recall: 0.9844 - tumor_type_accuracy: 0.6672 - tumor_type_loss: 0.1886 - val_loss: 0.3511 - val_tumor_presence_accuracy: 0.9825 - val_tumor_presence_auc: 0.9958 - val_tumor_presence_loss: 0.0176 - val_tumor_presence_precision: 0.9902 - val_tumor_presence_recall: 0.9854 - val_tumor_type_accuracy: 0.6369 - val_tumor_type_loss: 0.2509 - learning_rate: 1.5625e-05
Epoch 52/60
143/143 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - loss: 0.2675 - tumor_presence_accuracy: 0.9764 - tumor_presence_auc: 0.9964 - tumor_presence_loss: 0.0183 - tumor_presence_precision: 0.9849 - tumor_presence_recall: 0.9824 - tumor_type_accuracy: 0.6683 - tumor_type_loss: 0.1917
Epoch 52: ReduceLROnPlateau reducing learning rate to 7.812500371073838e-06.

Epoch 52: saving model to /kaggle/working/checkpoints/epoch_52.weights.h5
143/143 ━━━━━━━━━━━━━━━━━━━━ 26s 178ms/step - loss: 0.2675 - tumor_presence_accuracy: 0.9764 - tumor_presence_auc: 0.9964 - tumor_presence_loss: 0.0183 - tumor_presence_precision: 0.9849 - tumor_presence_recall: 0.9824 - tumor_type_accuracy: 0.6684 - tumor_type_loss: 0.1916 - val_loss: 0.3153 - val_tumor_presence_accuracy: 0.9816 - val_tumor_presence_auc: 0.9959 - val_tumor_presence_loss: 0.0173 - val_tumor_presence_precision: 0.9902 - val_tumor_presence_recall: 0.9842 - val_tumor_type_accuracy: 0.6518 - val_tumor_type_loss: 0.2240 - learning_rate: 1.5625e-05
Epoch 52: early stopping
1/1 ━━━━━━━━━━━━━━━━━━━━ 6s 6s/step

2026/02/04 17:12:07 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/02/04 17:12:35 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmpxkgyxukx/model, flavor: tensorflow). Fall back to return ['tensorflow==2.19.0', 'cloudpickle==3.1.1']. Set logging level to DEBUG to see the full traceback.
Registered model 'BrainTumorMRI_DenseNet121_2Head' already exists. Creating a new version of this model...
2026/02/04 17:12:59 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: BrainTumorMRI_DenseNet121_2Head, version 19
Created version '19' of model 'BrainTumorMRI_DenseNet121_2Head'.
/tmp/ipykernel_55/1980140685.py:39: FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
  latest_version = client.get_latest_versions(MODEL_NAME)[-1].version
/tmp/ipykernel_55/1980140685.py:41: FutureWarning: ``mlflow.tracking.client.MlflowClient.transition_model_version_stage`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
  client.transition_model_version_stage(

🏃 View run DenseNet121freeze=True_mask=True_20260204-1641 at: https://preachingly-nonabjuratory-marget.ngrok-free.dev/#/experiments/830660600119881173/runs/5557c30f1d2540b4ae30afa7f1d8b4f8
🧪 View experiment at: https://preachingly-nonabjuratory-marget.ngrok-free.dev/#/experiments/830660600119881173

## Epoch filter

In [57]:
history_df = pd.DataFrame(history.history)
history_df["epoch"] = history_df.index
#history_df.head(5)

In [58]:
metrics_cols = [
    "epoch",
    "val_tumor_presence_recall",
    "val_tumor_type_accuracy",
    "val_tumor_presence_loss",
    "val_tumor_type_loss"
]

df = history_df[metrics_cols].copy()

In [59]:
df = df[
    (df["val_tumor_presence_recall"] >= 0.94) &
    (df["val_tumor_type_accuracy"] >= 0.55)
]
#df

,epoch,val_tumor_presence_recall,val_tumor_type_accuracy,val_tumor_presence_loss,val_tumor_type_loss
12,12,0.995146,0.643920,0.037375,0.291258
13,13,0.984223,0.652668,0.023051,0.280522
15,15,0.997573,0.563430,0.046265,0.489436
17,17,0.987864,0.643920,0.023655,0.276753
24,24,0.981796,0.595801,0.024683,0.370762
25,25,0.945388,0.595801,0.030368,0.489721
26,26,0.985437,0.622922,0.019657,0.298615
27,27,0.987864,0.654418,0.020886,0.240111
28,28,0.951456,0.606299,0.028617,0.344925
29,29,0.952670,0.657043,0.027053,0.244568
30,30,0.976942,0.643920,0.021788,0.279142
31,31,0.973301,0.633421,0.022147,0.323054
32,32,0.974515,0.641295,0.022916,0.290061
33,33,0.986650,0.644794,0.018715,0.235125
34,34,0.985437,0.635171,0.018375,0.265081
35,35,0.990291,0.629921,0.017877,0.279372
36,36,0.973301,0.642170,0.019472,0.247968
37,37,0.979369,0.638670,0.018143,0.271019
38,38,0.981796,0.648294,0.019253,0.263211
39,39,0.983010,0.638670,0.018929,0.248109
40,40,0.980583,0.646544,0.018539,0.230408
41,41,0.984223,0.657918,0.018456,0.211605
42,42,0.985437,0.634296,0.017765,0.263757
43,43,0.985437,0.659668,0.018888,0.211857
44,44,0.978155,0.643920,0.018738,0.237881
45,45,0.985437,0.650044,0.018632,0.219664
46,46,0.989078,0.653543,0.020982,0.234484
47,47,0.985437,0.643920,0.018658,0.235738
48,48,0.983010,0.640420,0.018800,0.261859
49,49,0.985437,0.654418,0.017929,0.217380
50,50,0.985437,0.636920,0.017633,0.250928
51,51,0.984223,0.651794,0.017297,0.223997

In [60]:
def normalize(col):
    return (col - col.min()) / (col.max() - col.min() + 1e-8)

df["pres_rec_norm"] = normalize(df["val_tumor_presence_recall"])
df["type_accu_norm"] = normalize(df["val_tumor_type_accuracy"])
df["pres_loss_norm"] = 1 - normalize(df["val_tumor_presence_loss"])
df["type_loss_norm"] = 1 - normalize(df["val_tumor_type_loss"])

In [61]:
df["S"] = (
    0.40 * df["pres_rec_norm"]
  + 0.35 * df["type_accu_norm"]
  + 0.15 * df["pres_loss_norm"]
  + 0.10 * df["type_loss_norm"]
)
#df

,epoch,val_tumor_presence_recall,val_tumor_type_accuracy,val_tumor_presence_loss,val_tumor_type_loss,pres_rec_norm,type_accu_norm,pres_loss_norm,type_loss_norm,S
12,12,0.995146,0.643920,0.037375,0.291258,0.953487,0.836364,3.068861e-01,7.135993e-01,0.791515
13,13,0.984223,0.652668,0.023051,0.280522,0.744186,0.927273,8.013507e-01,7.522013e-01,0.817642
15,15,0.997573,0.563430,0.046265,0.489436,1.000000,0.000000,3.452097e-07,1.022647e-03,0.400102
17,17,0.987864,0.643920,0.023655,0.276753,0.813953,0.836364,7.804953e-01,7.657535e-01,0.811958
24,24,0.981796,0.595801,0.024683,0.370762,0.697674,0.336363,7.450067e-01,4.277307e-01,0.551321
25,25,0.945388,0.595801,0.030368,0.489721,0.000000,0.336363,5.487592e-01,3.595632e-08,0.200041
26,26,0.985437,0.622922,0.019657,0.298615,0.767442,0.618181,9.185372e-01,6.871437e-01,0.729835
27,27,0.987864,0.654418,0.020886,0.240111,0.813953,0.945454,8.761143e-01,8.975031e-01,0.877658
28,28,0.951456,0.606299,0.028617,0.344925,0.116278,0.445454,6.092224e-01,5.206315e-01,0.345867
29,29,0.952670,0.657043,0.027053,0.244568,0.139535,0.972727,6.631980e-01,8.814796e-01,0.583896
30,30,0.976942,0.643920,0.021788,0.279142,0.604651,0.836364,8.449552e-01,7.571615e-01,0.737047
31,31,0.973301,0.633421,0.022147,0.323054,0.534884,0.727273,8.325634e-01,5.992714e-01,0.653310
32,32,0.974515,0.641295,0.022916,0.290061,0.558139,0.809091,8.060323e-01,7.179035e-01,0.699132
33,33,0.986650,0.644794,0.018715,0.235125,0.790697,0.845454,9.510466e-01,9.154317e-01,0.846388
34,34,0.985437,0.635171,0.018375,0.265081,0.767442,0.745454,9.627756e-01,8.077211e-01,0.793074
35,35,0.990291,0.629921,0.017877,0.279372,0.860464,0.690909,9.799591e-01,7.563349e-01,0.808631
36,36,0.973301,0.642170,0.019472,0.247968,0.534884,0.818181,9.248990e-01,8.692526e-01,0.725977
37,37,0.979369,0.638670,0.018143,0.271019,0.651162,0.781818,9.707937e-01,7.863693e-01,0.758357
38,38,0.981796,0.648294,0.019253,0.263211,0.697674,0.881818,9.324571e-01,8.144445e-01,0.809019
39,39,0.983010,0.638670,0.018929,0.248109,0.720929,0.781818,9.436444e-01,8.687460e-01,0.790429
40,40,0.980583,0.646544,0.018539,0.230408,0.674418,0.863636,9.571178e-01,9.323922e-01,0.808847
41,41,0.984223,0.657918,0.018456,0.211605,0.744186,0.981818,9.600000e-01,1.000000e+00,0.885310
42,42,0.985437,0.634296,0.017765,0.263757,0.767442,0.736363,9.838244e-01,8.124807e-01,0.793526
43,43,0.985437,0.659668,0.018888,0.211857,0.767442,1.000000,9.450796e-01,9.990963e-01,0.898648
44,44,0.978155,0.643920,0.018738,0.237881,0.627906,0.836364,9.502584e-01,9.055211e-01,0.776980
45,45,0.985437,0.650044,0.018632,0.219664,0.767442,0.900000,9.538938e-01,9.710254e-01,0.862163
46,46,0.989078,0.653543,0.020982,0.234484,0.837209,0.936363,8.727854e-01,9.177358e-01,0.885302
47,47,0.985437,0.643920,0.018658,0.235738,0.767442,0.836364,9.530055e-01,9.132282e-01,0.833978
48,48,0.983010,0.640420,0.018800,0.261859,0.720929,0.800000,9.481235e-01,8.193064e-01,0.792521
49,49,0.985437,0.654418,0.017929,0.217380,0.767442,0.945454,9.781762e-01,9.792362e-01,0.882536
50,50,0.985437,0.636920,0.017633,0.250928,0.767442,0.763636,9.883804e-01,8.586106e-01,0.808367
51,51,0.984223,0.651794,0.017297,0.223997,0.744186,0.918182,1.000000e+00,9.554454e-01,0.864582

In [62]:
best_row = df.sort_values("S", ascending=False).iloc[0]
best_epoch = int(best_row["epoch"])

print(f"✅ Best epoch selected from S: {best_epoch}")
print(best_row)

✅ Best epoch selected from S: 43
epoch                        43.000000
val_tumor_presence_recall     0.985437
val_tumor_type_accuracy       0.659668
val_tumor_presence_loss       0.018888
val_tumor_type_loss           0.211857
pres_rec_norm                 0.767442
type_accu_norm                1.000000
pres_loss_norm                0.945080
type_loss_norm                0.999096
S                             0.898648
Name: 43, dtype: float64

In [68]:
mlflow.set_tags({
    "model_stage": "best_manual_epoch",
    "best_epoch": best_epoch,
    "selection_method": "composite_score_S",
})

mlflow.log_metric("S", best_row.iloc[-1])
mlflow.log_metric("Best epoch", best_row.iloc[0])

In [69]:
model.load_weights(f"{CHECKPOINT_DIR}/epoch_{best_epoch:02d}.weights.h5")
print(f"✅ Loaded best epoch: {best_epoch}")

✅ Loaded best epoch: 43

In [70]:
mlflow.tensorflow.log_model(
    model,
    name=f"best_epoch_{best_epoch}_manual",
    registered_model_name=MODEL_NAME
)
print(f"✅ Registered best model: {MODEL_NAME}")

2026/02/04 17:46:33 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.
2026/02/04 17:46:45 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: /tmp/tmp1fggz53y/model, flavor: tensorflow). Fall back to return ['tensorflow==2.19.0', 'cloudpickle==3.1.1']. Set logging level to DEBUG to see the full traceback.
Registered model 'BrainTumorMRI_DenseNet121_2Head' already exists. Creating a new version of this model...
2026/02/04 17:46:59 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: BrainTumorMRI_DenseNet121_2Head, version 22
Created version '22' of model 'BrainTumorMRI_DenseNet121_2Head'.

✅ Registered best model: BrainTumorMRI_DenseNet121_2Head

In [72]:
model.save(f"{MODEL_DIR}/brain_tumor_model_best_epoch_{best_epoch}.keras")
model.save_weights(
    f"{MODEL_DIR}/brain_tumor_weights_epoch_{best_epoch}.weights.h5"
)
mlflow.log_artifacts(MODEL_DIR, artifact_path="exported_model_files")

### Loading final model from MLFlow

In [80]:
model = mlflow.tensorflow.load_model(
    "models:/BrainTumorMRI_DenseNet121_2Head/latest"
)
print("✅ Model loaded successfully with custom loss")

Downloading artifacts:   0%|          | 0/7 [00:00<?, ?it/s]

✅ Model loaded successfully with custom loss

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'loss_scale_optimizer', because it has 19 variables whereas the saved optimizer has 32 variables.
  saveable.load_own_variables(weights_store.get(inner_path))
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 15 variables whereas the saved optimizer has 28 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [81]:
model.summary()

Model: "densenet_two_head"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_6       │ (None, 260, 260,  │          0 │ -                 │
│ (InputLayer)        │ 3)                │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ data_augmentation_… │ (None, 260, 260,  │          0 │ input_layer_6[0]… │
│ (Sequential)        │ 3)                │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ densenet121         │ (None, 8, 8,      │  7,037,504 │ data_augmentatio… │
│ (Functional)        │ 1024)             │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ global_average_poo… │ (None, 1024)      │          0 │ densenet121[0][0] │
│ (GlobalAveragePool… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_9 (Dense)     │ (None, 512)       │    524,288 │ global_average_p… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 512)       │      2,048 │ dense_9[0][0]     │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_5        │ (None, 512)       │          0 │ batch_normalizat… │
│ (Activation)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_5 (Dropout) │ (None, 512)       │          0 │ activation_5[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ tumor_presence      │ (None, 1)         │     66,177 │ dropout_5[0][0]   │
│ (Sequential)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ tumor_type          │ (None, 4)         │     66,564 │ dropout_5[0][0]   │
│ (Sequential)        │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 8,354,128 (31.87 MB)

 Trainable params: 657,541 (2.51 MB)

 Non-trainable params: 7,039,040 (26.85 MB)

 Optimizer params: 657,547 (2.51 MB)

In [82]:
model.evaluate(val_ds)

36/36 ━━━━━━━━━━━━━━━━━━━━ 12s 120ms/step - loss: 0.3289 - tumor_presence_accuracy: 0.9850 - tumor_presence_auc: 0.9958 - tumor_presence_loss: 0.0168 - tumor_presence_precision: 0.9880 - tumor_presence_recall: 0.9916 - tumor_type_accuracy: 0.6632 - tumor_type_loss: 0.2400

/usr/local/lib/python3.12/dist-packages/keras/src/trainers/epoch_iterator.py:160: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

[0.3676888942718506,
 0.017765367403626442,
 0.2637573480606079,
 0.9816272854804993,
 0.9955679774284363,
 0.9890377521514893,
 0.9854369163513184,
 0.6342957019805908]

### Confusion Matrix

### Grad-CAM

## Fine-Tuning

In [66]:
Warning : do not forget :
- mtrx confu classif
- XAI (Grad-CAM ?)
- stratégie de fine-tuning du backbone
- BatchNormalization precaution in fine-tuning

SyntaxError: invalid syntax (560267976.py, line 1)